#!/bin/bash
# uses find to avoid touching files that already have the right permissions
# right permissions are:
# world rX, we have no guarantees of uids or gids upon
# deployment so we want files accessible to all.

set -e
for d in "$@"; do
  find "$d" \
    ! -perm -o+rX  \
    -exec chmod o+rX {} \;
done
