# Configuration for ./workflows/release-notes-sync
# Ref: https://github.com/BetaHuhn/repo-file-sync-action

group:
  repos: nebari-dev/nebari-docs
  files:
    - source: RELEASE.md
      dest: docs/docs/references/RELEASE.md
