# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: run-k8s-tests
    # Cloud Provider: AWS
    cloud: aws
    # Instance Type has 4 vcpu, 16 GiB memory, Up to 5 Gbps Network Performance
    instance_type: t3a.xlarge
    # Custom AMI with docker is pre-installed
    machine_image: ami-0ff297f01f579288c
    # Region: Oregon
    region: us-west-2
    # Use Spot Instances for cost savings
    preemptible: false
    labels:
      - cirun-runner
