# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: run-k8s-tests
    # Cloud Provider: DigitalOcean
    cloud: aws
    # Cheapest VM on DigitalOcean
    instance_type: t3a.xlarge
    # Ubuntu-20.4 image"
    machine_image: ami-08939857cf6893cde
    region: us-west-2
    # Path of the relevant workflow file
    workflow: .github/workflows/kubernetes_test.yaml
    preemptible: true
    # Number of runners to provision on every trigger on Actions job
    # 3 because testing on Python 3.7, 3.8
    # See .github/workflows/build-gpu.yml
    count: 1