# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: run-k8s-tests
    # Cloud Provider: AWS
    cloud: aws
    # Instance Type has 8 vcpu, 64 GiB memory, Up to 10 Gbps Network Performance
    instance_type: r5a.2xlarge
    # Custom Ubuntu 24.04 AMI with docker/hub pre-installed
    machine_image: ami-01b494943951b97c7
    # Region: Oregon
    region: us-west-2
    # Use Spot Instances for cost savings
    preemptible:
      - true
      - false
    labels:
      - cirun-runner
    extra_config:
      monitoring: true
