# Self-Hosted Github Action Runners on DigitalOcean via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: run-k8s-tests
    # Cloud Provider: AWS
    cloud: aws
    # ec2 instance
    instance_type: m5.xlarge
    # Ubuntu-20.4, ami image"
    machine_image: ami-06fd8a495a537da8b
    # Ability to interrupt ec2-instance
    preemptible: false
    # Region
    region: us-east-1 # not sure this does anything
    # Path of the relevant workflow file
    workflow: .github/workflows/kubernetes_test.yaml
    # Number of runners to provision on every trigger on Actions job
    count: 1
