# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: run-k8s-tests
    # Cloud Provider: AWS
    cloud: aws
    # Instance Type has 16 vcpu, 64 GiB memory, Up to 5 Gbps Network Performance
    instance_type: m6a.4xlarge
    # Custom Ubuntu 24.04 AMI with docker/hub pre-installed
    machine_image: ami-01b494943951b97c7
    # Region: Oregon
    region: us-west-2
    # Use Spot Instances for cost savings
    preemptible:
      - true
      - false
    labels:
      - cirun-runner
