ingress:
  # Helm chart (14.0 anyway) will only define Ingress records, not IngressRoute as required by Traefik, so
  # we will need to define our own IngressRoute elsewhere.
  enabled: false

extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG

startupScripts:
  keycloak.cli: |
    {{- .Files.Get "scripts/keycloak.cli" | nindent 2 }}

  qhubadminuser.sh: |
    /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p password

# Don't think this works, because the server is not yet running...
#  qhubrealm.sh: |
#    /opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password testpass
#    /opt/jboss/keycloak/bin/kcadm.sh update realms/master -s displayName=Keycloak661
