{
 "title": "JupyterHub Dashboard",
 "tags": [ "jupyterhub" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "hub",
    "query": {
     "query": "label_values({service=\"hub\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hub usage stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Active Users",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  group(\n    kube_pod_status_phase{phase=\"Running\"}\n  ) by (label_component, pod, namespace)\n  * on (namespace, pod) group_right() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (namespace)\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "User Resource Utilization stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "User active age distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(\n  time()\n  - (\n    kube_pod_created{job='kube-state-metrics'}\n    * on (namespace, pod) group_left()\n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n  )\n)\n"
    }
   ]
  },
  {
   "title": "User CPU usage distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  irate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\n  * on (namespace, pod) group_left(container) \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "User memory usage distribution",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  container_memory_working_set_bytes{name!=\"\"}\n  * on (namespace, pod) group_left(container) \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (pod)\n"
    }
   ]
  },
  { "title": "Hub Diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Server Start Times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jupyterhub_server_spawn_duration_seconds_bucket{}[5m])) by (le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(jupyterhub_server_spawn_duration_seconds_bucket{}[5m])) by (le))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Server Start Failures",
   "type": "graph",
   "description": "Attempts by users to start servers that failed.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jupyterhub_server_spawn_duration_seconds_count{status!=\"success\"}[2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Hub response latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(\n      jupyterhub_request_duration_seconds_bucket{\n        # Ignore SpawnProgressAPIHandler, as it is a EventSource stream\n        # and keeps long lived connections open\n        handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n      }[5m]\n    )\n  ) by (le))\n",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum(\n    rate(\n      jupyterhub_request_duration_seconds_bucket{\n        app=\"jupyterhub\",\n        namespace=~\"$hub\",\n        # Ignore SpawnProgressAPIHandler, as it is a EventSource stream\n        # and keeps long lived connections open\n        handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n      }[5m]\n    )\n  ) by (le))\n",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "All JupyterHub Components CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n# with both no name and `name=k8s_...`,\n# in which case sum() reports double the actual metric\nirate(container_cpu_usage_seconds_total{name!=\"\"}[5m])\n\n  * on (namespace, pod) group_left(container, label_component) \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component!=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (label_component)\n",
     "legendFormat": "{{ label_component }}"
    }
   ]
  },
  {
   "title": "All JupyterHub Components Memory (Working Set)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n# with both no name and `name=k8s_...`,\n# in which case sum() reports double the actual metric\ncontainer_memory_working_set_bytes{name!=\"\"}\n\n  * on (namespace, pod) group_left(container, label_component) \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component!=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (label_component)\n",
     "legendFormat": "{{ label_component }}"
    }
   ]
  },
  {
   "title": "Hub DB Disk Space Availability %",
   "type": "graph",
   "description": "% of disk space left in the disk storing the JupyterHub sqlite database. If goes to 0, the hub will fail.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "# Free bytes available on the hub db PVC\nsum(kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"hub-db-dir\", namespace=~\"$hub\"}) by (namespace) /\n# Total number of bytes available on the hub db PVC\nsum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"hub-db-dir\", namespace=~\"$hub\"}) by (namespace)\n",
     "legendFormat": "{{ $hub }}"
    }
   ]
  },
  {
   "title": "Non Running Pods",
   "type": "graph",
   "description": "Pods in a non-running state in the hub's namespace.\n\nPods stuck in non-running states often indicate an error condition\n",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_status_phase{phase!=\"Running\", namespace=~\"$hub\"}\n) by (phase)\n",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Users per node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    # kube_pod_info.node identifies the pod node,\n    # while kube_pod_labels.node is the metrics exporter's node\n    kube_pod_info{node!=\"\"}\n    * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (node)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Anomalous user pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Very old user pods",
   "type": "table-old",
   "description": "User pods that have been running for a long time (>8h).\n\nThis often indicates problems with the idle culler\n",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "(\n  time() - (kube_pod_created * on (namespace, pod) group_left\n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace))\n)  > (60 * 60 * 8) # 8 hours is our threshold\n",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "User Pods with high CPU usage (>0.5)",
   "type": "table-old",
   "description": "User pods using a lot of CPU\n\nThis could indicate a runaway process consuming resources\nunnecessarily.\n",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "max( # Ideally we just want 'current' value, so max will do\n  irate(container_cpu_usage_seconds_total[5m])\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (namespace, pod) > 0.5\n",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "User pods with high memory usage (>80% of limit)",
   "type": "table-old",
   "description": "User pods getting close to their memory limit\n\nOnce they hit their memory limit, user kernels will start dying.\n",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "max( # Ideally we just want 'current', but max will do. This metric is a gauge, so sum is inappropriate\n  container_memory_working_set_bytes\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (namespace, pod)\n/\nsum(\n  kube_pod_container_resource_limits{resource=\"memory\"}\n  * on (namespace, pod) group_left() \n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}\n  ) by (pod, namespace)\n) by (namespace, pod)\n> 0.8\n",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}