# https://github.com/codecentric/helm-charts/blob/keycloak-15.0.2/charts/keycloak/values.yaml
ingress:
  # Helm chart (14.0 anyway) will only define Ingress records, not IngressRoute as required by Traefik, so
  # we will need to define our own IngressRoute elsewhere.
  enabled: false

image:
  repository: quay.io/keycloak/keycloak

imagePullSecrets:
  - name: "extcrcreds"

extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"

startupScripts:
  keycloak.cli: |
    {{- .Files.Get "scripts/keycloak.cli" | nindent 2 }}

  nebariadminuser.sh: |
    /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u root -p "{{ .Values.initial_root_password }}"
    /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u nebari-bot -p "{{ .Values.nebari_bot_password }}"

  mv-custom-themes.sh: |
    #!/bin/sh
    printf '=%.0s' {1..73}
    echo "Start moving custom themes to /opt/jboss/keycloak/themes"

    if [ -d /opt/data/custom-themes/themes ]; then
      echo 'Copying custom themes from /opt/data/custom-themes/themes to /opt/jboss/keycloak/themes'
      cp -r /opt/data/custom-themes/themes/* /opt/jboss/keycloak/themes/
    else
      echo 'No custom themes found in /opt/data/custom-themes'
    fi

    echo "Finished moving custom themes"
    printf '=%.0s' {1..73}

extraInitContainers: |
  - command:
    - sh
    - -c
    - |
      if [ ! -f /data/keycloak-metrics-spi-2.5.3.jar ]; then
        wget https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -P /data/ &&
        export SHA256SUM=9b3f52f842a66dadf5ff3cc3a729b8e49042d32f84510a5d73d41a2e39f29a96 &&
        if ! (echo "$SHA256SUM  /data/keycloak-metrics-spi-2.5.3.jar" | sha256sum -c)
          then
            echo "Error: Checksum not verified" && exit 1
          else
            chown 1000:1000 /data/keycloak-metrics-spi-2.5.3.jar &&
            chmod 777 /data/keycloak-metrics-spi-2.5.3.jar
        fi
      else
        echo "File /data/keycloak-metrics-spi-2.5.3.jar already exists. Skipping download."
      fi
    image: busybox:1.36
    name: initialize-spi-metrics-jar
    securityContext:
      runAsUser: 0
    volumeMounts:
      - name: metrics-plugin
        mountPath: /data
  {{- if .Values.customThemes.enabled }}
  - env:
    - name: GIT_SYNC_REPO
      value: {{ .Values.customThemes.repository }}
    - name: GIT_SYNC_BRANCH
      value: {{ .Values.customThemes.branch }}
    - name: GIT_SYNC_ONE_TIME
      value: "true"
    - name: GIT_SYNC_GROUP_WRITE
      value: "true"
    - name: GIT_SYNC_ROOT
      value: /opt/data/custom-themes
    - name: GIT_SYNC_DEST
      value: themes
    - name: GIT_SYNC_SSH
      value: "false"
    image: k8s.gcr.io/git-sync:v3.1.5
    imagePullPolicy: IfNotPresent
    name: keycloak-git-sync
    resources: {}
    securityContext:
      runAsGroup: 1000
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/data/custom-themes
      name: custom-themes
  {{- end }}

extraVolumeMounts: |
  - name: metrics-plugin
    mountPath: /opt/jboss/keycloak/providers/
  - mountPath: /opt/data/custom-themes
    name: custom-themes

extraVolumes: |
  - name: metrics-plugin
    emptyDir: {}
  - name: custom-themes
    emptyDir: {}
