blank_issues_enabled: false
contact_links:
  - name: Nebari Documentation 📖
    url: https://docs.nebari.dev/en/stable/
    about: Read Nebari docs and development guide.
  - name: GitHub discussions 💬
    url: https://github.com/Quansight/nebari/discussions
    about: Keep up to date with the community discussions
  - name: "(maintainers only) Blank issue"
    url: https://github.com/Quansight/nebari/issues/new
    about: For maintainers only - should be used sparingly
