name: "Feature request"
description: "Create a feature request to help us improve"
title: "[ENH] - <title>"
labels: ["type: enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Hi! Thanks for using Nebari and taking some time to contribute to Nebari.
  - type: textarea
    attributes:
      label: Feature description
      description: |
        Describe what you are proposing. Provide as much context as possible and link to related issues and/or pull requests.
        This section should contain "what" you are proposing.
        Are you having any problems? Briefly describe what your painpoints are. For example: "I'm always frustrated when ..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Value and/or benefit
      description: |
        What is the value in adding this feature, and who will benefit from it? Include any information that could help us prioritize the issue.
        This section should contain "why" this issue should be resolved.
        ✨ If this is for a new feature or enhancement, consider adding [user stories](https://www.atlassian.com/agile/project-management/user-stories).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
