name: base
channels:
  - conda-forge
dependencies:
 - pip==21.1.2
 - jupyterhub==1.5.0
 - jupyterhub-kubespawner==1.1.0
 - oauthenticator==14.1.0
 - escapism==1.0.1
 - cdsdashboards==0.6.1
 - jupyterhub-idle-culler==1.0
 - pip:
   - qhub-jupyterhub-theme==0.3.5
   - python-keycloak==0.26.1
