{
 "title": "NFS and Support Information",
 "tags": [
  "support",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "NFS diagnostics", "type": "row", "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "User Nodes NFS Ops",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_nfs_requests_total[5m])) by (node) > 0",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "iowait % on each node",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_nfs_requests_total[5m])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "NFS Operation Types on user nodes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_nfs_requests_total[5m])) by (method) > 0",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "NFS Server CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{job=\"prometheus-nfsd-server\", mode!=\"idle\"}[2m])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "NFS Server Disk ops",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_nfsd_disk_bytes_read_total[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_nfsd_disk_bytes_written_total[5m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "NFS Server disk write latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{job=\"prometheus-nfsd-server\"}[5m])) by (device) / sum(rate(node_disk_writes_completed_total{job=\"prometheus-nfsd-server\"}[5m])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "NFS Server disk read latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{job=\"prometheus-nfsd-server\"}[5m])) by (device) / sum(rate(node_disk_reads_completed_total{job=\"prometheus-nfsd-server\"}[5m])) by (device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Support system diagnostics", "type": "row", "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 } },
  {
   "title": "Prometheus CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"support-prometheus-server-.*\",namespace=\"support\"}[5m]))"
    }
   ]
  },
  {
   "title": "Prometheus Memory (Working Set)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"support-prometheus-server-.*\", namespace=\"support\"})"
    }
   ]
  },
  {
   "title": "Prometheus Free Disk space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"support\",persistentvolumeclaim=\"support-prometheus-server\"})"
    }
   ]
  },
  {
   "title": "Prometheus Network Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"support-prometheus-server-.*\",namespace=\"support\"}[5m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(container_network_send_bytes_total{pod=~\"support-prometheus-server-.*\",namespace=\"support\"}[5m]))",
     "legendFormat": "send"
    }
   ]
  }
 ]
}