{
 "title": "User Pod Diagnostics Dashboard",
 "tags": [ "jupyterhub" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "hub",
    "query": "label_values(kube_service_labels{service=\"hub\"}, namespace)"
   },
   {
    "name": "user_pod",
    "query": "label_values(kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}, pod)"
   },
   {
    "name": "instance",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Per-user per-server memory usage\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  container_memory_working_set_bytes{name!=\"\", instance=~\"$instance\"}\n  * on (namespace, pod) group_left(container) \n  group(\n      kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\"$user_pod\"}\n  ) by (pod, namespace)\n) by (pod)\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Per-user per-server CPU usage\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  irate(container_cpu_usage_seconds_total{name!=\"\", instance=~\"$instance\"}[5m])\n  * on (namespace, pod) group_left(container) \n  group(\n      kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\"$user_pod\"}\n  ) by (pod, namespace)\n) by (pod)\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "graph",
   "description": "Per-user per-server memory Requests\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\"$instance\"}\n) by (pod, namespace)\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "graph",
   "description": "Per-user per-server CPU Requests\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$hub\", node=~\"$instance\"}\n) by (pod, namespace)\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  }
 ]
}