name: "Authenticate to Cloud Provider"
description: "Retrieve secrets from Vault and authenticate to the specified cloud provider"

inputs:
  provider:
    description: "The cloud provider to authenticate to (gcp, aws, azure or do)"
    required: true
  cloudflare_token:
    description: "Retrieve Cloudflare token from Vault"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    ############ GCP ############
    - name: Retrieve GCP Secrets from Vault
      if: ${{ inputs.provider == 'gcp' }}
      uses: hashicorp/vault-action@v3.0.0
      with:
        method: jwt
        url: "https://quansight-vault-public-vault-b2379fa7.d415e30e.z1.hashicorp.cloud:8200"
        namespace: "admin/quansight"
        role: "repository-nebari-dev-nebari-role"
        secrets: |
          kv/data/repository/nebari-dev/nebari/google_cloud_platform/nebari-dev-ci/github-nebari-dev-repo-ci project_id | PROJECT_ID;
          kv/data/repository/nebari-dev/nebari/google_cloud_platform/nebari-dev-ci/github-nebari-dev-repo-ci workload_identity_provider | GCP_WORKFLOW_PROVIDER;
          kv/data/repository/nebari-dev/nebari/google_cloud_platform/nebari-dev-ci/github-nebari-dev-repo-ci service_account_name | GCP_SERVICE_ACCOUNT;

    - name: Authenticate to GCP
      if: ${{ inputs.provider == 'gcp' }}
      uses: "google-github-actions/auth@v1"
      with:
        token_format: access_token
        create_credentials_file: "true"
        workload_identity_provider: ${{ env.GCP_WORKFLOW_PROVIDER }}
        service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

    - name: Set GCP Environment Variable
      if: ${{ inputs.provider == 'gcp' }}
      shell: bash
      run: |
        echo "GOOGLE_CREDENTIALS=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV

    ############ AWS ############
    - name: Retrieve AWS Secrets from Vault
      if: ${{ inputs.provider == 'aws' }}
      uses: hashicorp/vault-action@v3.0.0
      with:
        method: jwt
        url: "https://quansight-vault-public-vault-b2379fa7.d415e30e.z1.hashicorp.cloud:8200"
        namespace: "admin/quansight"
        role: "repository-nebari-dev-nebari-role"
        secrets: |
          kv/data/repository/nebari-dev/nebari/amazon_web_services/nebari-dev-ci role_name | AWS_ROLE_ARN;

    - name: Authenticate to AWS
      if: ${{ inputs.provider == 'aws' }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-session-name: github-action
        aws-region: us-east-1

    ############ Azure ############
    - name: Retrieve Azure Secrets from Vault
      if: ${{ inputs.provider == 'azure' }}
      uses: hashicorp/vault-action@v3.0.0
      with:
        method: jwt
        url: "https://quansight-vault-public-vault-b2379fa7.d415e30e.z1.hashicorp.cloud:8200"
        namespace: "admin/quansight"
        role: "repository-nebari-dev-nebari-role"
        secrets: |
          kv/data/repository/nebari-dev/nebari/azure/nebari-dev-ci/github-nebari-dev-repo-ci client_id | ARM_CLIENT_ID;
          kv/data/repository/nebari-dev/nebari/azure/nebari-dev-ci/github-nebari-dev-repo-ci tenant_id | ARM_TENANT_ID;
          kv/data/repository/nebari-dev/nebari/azure/nebari-dev-ci/github-nebari-dev-repo-ci subscription_id | ARM_SUBSCRIPTION_ID;

    - name: Azure Login
      if: ${{ inputs.provider == 'azure' }}
      uses: azure/login@v1
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

    ############ Digital Ocean ############
    - name: Retrieve Shared Secrets from Vault
      if: ${{ inputs.provider == 'do' }}
      uses: hashicorp/vault-action@v3.0.0
      with:
        method: jwt
        url: "https://quansight-vault-public-vault-b2379fa7.d415e30e.z1.hashicorp.cloud:8200"
        namespace: "admin/quansight"
        role: "repository-nebari-dev-nebari-role"
        secrets: |
          kv/data/repository/nebari-dev/nebari/shared_secrets DIGITALOCEAN_TOKEN | DIGITALOCEAN_TOKEN;
          kv/data/repository/nebari-dev/nebari/shared_secrets SPACES_ACCESS_KEY_ID | SPACES_ACCESS_KEY_ID;
          kv/data/repository/nebari-dev/nebari/shared_secrets SPACES_SECRET_ACCESS_KEY | SPACES_SECRET_ACCESS_KEY;

    - name: Set Environment DO
      shell: bash
      run: |
        echo "SPACES_ACCESS_KEY_ID=${{ secrets.SPACES_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "SPACES_SECRET_ACCESS_KEY=${{ secrets.SPACES_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "NEBARI_K8S_VERSION"=1.25.12-do.0 >> $GITHUB_ENV

    ############ Cloudflare ############
    - name: Retrieve Cloudflare Token from Vault
      if: ${{ inputs.cloudflare_token == 'true' }}
      uses: hashicorp/vault-action@v3.0.0
      with:
        method: jwt
        url: "https://quansight-vault-public-vault-b2379fa7.d415e30e.z1.hashicorp.cloud:8200"
        namespace: "admin/quansight"
        role: "repository-nebari-dev-nebari-role"
        secrets: |
          kv/data/repository/nebari-dev/nebari/cloudflare/internal-devops@quansight.com/nebari-dev-ci
          token | CLOUDFLARE_TOKEN;
