#!/usr/bin/env bash
set -euo pipefail

# A workaround that allows a command to run in a
# specific conda environment
cat <<EOF > /opt/conda-run-worker
#!/bin/bash
set -xe

source activate \$CONDA_ENVIRONMENT
dask-worker "\$@"
EOF

cat <<EOF > /opt/conda-run-scheduler
#!/bin/bash
set -xe

source activate \$CONDA_ENVIRONMENT
dask-scheduler "\$@"
EOF

chmod 755 /opt/conda-run-worker
chmod 755 /opt/conda-run-scheduler
