# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "2022.11.0.dev1+g27f7945.d20221025110904"
__version_tuple__ = version_tuple = (2022, 11, 0, "dev1", "g27f7945.d20221025110904")
