metadata:
  name: ${var.name}-daskgateway-gateway
  namespace: var.namespace

spec:
  replicas: 1
  selector:
    match_labels:
      app.kubernetes.io/component: dask-gateway-gateway
  
  template:
    metadata:
      
      labels: 
        app.kubernetes.io/component: dask-gateway-gateway
      
      annotations:
        checksum/config-map: sha256(jsonencode(kubernetes_config_map.gateway.data))
        checksum/secret: sha256(jsonencode(kubernetes_secret.gateway.data))
    
    spec:
      affinity:
        node_affinity:
          required_during_scheduling_ignored_during_execution:
            node_selector_term:
              match_expressions:
                key: var.general-node-group.key
                operator: In
                values: var.general-node-group.value

