# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml
hub:
  db:
    type: sqlite-pvc
    pvc:
      storage: 1Gi
  baseUrl: "/"
  networkPolicy:
    enabled: false

proxy:
  secretToken: "<placeholder>"
  service:
    type: ClusterIP

scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: false
    replicas: 1

imagePullSecrets:
  - extcrcreds

singleuser:
  defaultUrl: "/lab"
  startTimeout: 600  # 10 minutes
  profileList: []
  storage:
    type: static
    extraVolumeMounts:
      - mountPath: "/home/shared"
        name: home
        subPath: "home/shared"
  cpu:
    limit: 1
    guarantee: 1
  memory:
    limit: "1G"
    guarantee: "1G"
  networkPolicy:
    enabled: false
