{
 "title": "Usage Report",
 "tags": [
  "jupyterhub",
  "dask"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "hub",
    "query": "label_values(kube_service_labels{service=\"hub\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "User pod memory usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 25, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_labels{\n  label_app=\"jupyterhub\",\n  label_component=\"singleuser-server\",\n  namespace=~\"$hub\"\n}\n* on (namespace, pod) group_left()\nsum(\n  container_memory_working_set_bytes{\n    namespace=~\"$hub\",\n    container=\"notebook\",\n    hub_jupyter_org_node_purpose=\"user\",\n    name!=\"\",\n  }\n) by (namespace, pod)\n",
     "legendFormat": "{{label_hub_jupyter_org_username}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Dask-gateway worker pod memory usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 25, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{\n    namespace=~\"$hub\",\n    label_app_kubernetes_io_component=\"dask-worker\",\n  }\n  * on (namespace, pod) group_left()\n  sum(\n    container_memory_working_set_bytes{\n      namespace=~\"$hub\",\n      container=\"dask-worker\",\n      k8s_dask_org_node_purpose=\"worker\",\n      name!=\"\",\n    }\n  ) by (namespace, pod)\n) by (label_hub_jupyter_org_username, label_gateway_dask_org_cluster)\n",
     "legendFormat": "{{label_hub_jupyter_org_username}}-{{label_gateway_dask_org_cluster}}"
    }
   ]
  },
  {
   "title": "Dask-gateway scheduler pod memory usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 25, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{\n    namespace=~\"$hub\",\n    label_app_kubernetes_io_component=\"dask-scheduler\",\n  }\n  * on (namespace, pod) group_left()\n  sum(\n    container_memory_working_set_bytes{\n      namespace=~\"$hub\",\n      container=\"dask-scheduler\",\n      k8s_dask_org_node_purpose=\"scheduler\",\n      name!=\"\",\n    }\n  ) by (namespace, pod)\n) by (label_hub_jupyter_org_username, label_gateway_dask_org_cluster)\n",
     "legendFormat": "{{label_hub_jupyter_org_username}}-{{label_gateway_dask_org_cluster}}"
    }
   ]
  },
  {
   "title": "GPU pod memory usage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 25, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_labels{\n  label_app=\"jupyterhub\",\n  label_component=\"singleuser-server\",\n  namespace=~\"$hub\"\n}\n* on (namespace, pod) group_left()\nsum(\n  container_memory_working_set_bytes{\n    namespace=~\"$hub\",\n    container=\"notebook\",\n    hub_jupyter_org_node_purpose=\"user\",\n    cloud_google_com_gke_nodepool=\"nb-gpu-k80\",\n    cloud_google_com_gke_accelerator=\"nvidia-tesla-k80\",\n    name!=\"\",\n  }\n) by (namespace, pod)\n",
     "legendFormat": "{{label_hub_jupyter_org_username}}-{{label_gateway_dask_org_cluster}}"
    }
   ]
  }
 ]
}