hub:
  extraConfig:
    jupyterhub_extra_config: |
{% filter indent(width=6) %}
{% include "templates/jupyterhub_config.py.j2" %}
{% endfilter %}

{% if cookiecutter.jupyterhub is defined and cookiecutter.jupyterhub.overrides is defined and cookiecutter.jupyterhub.overrides.hub is defined and cookiecutter.jupyterhub.overrides.hub.extraConfig is defined %}
{% filter indent(width=4) %}
{{ cookiecutter.jupyterhub.overrides.hub.extraConfig | default({}) | yamlify -}}
{% endfilter %}
{% endif %}

singleuser:
  storage:
    homeMountPath: /home/jovyan

cull:
  enabled: true
  timeout: 1800 # cull after 30min of inactivity
  every: 600
