name: Update API docs

on:
  push

env:
  FOOBAR: ${{ secrets.NEBARI_SENSEI_API_DOCS_PR_OPENER }}

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./docs-sphinx
    steps:
      - name: Check out repository 🛎️
        uses: actions/checkout@v4
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.23
