name: "Integration Tests"

on:
  schedule:
    - cron: "0 0 * * MON"
  workflow_dispatch:

env:
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

jobs:
  test-integration:
    name: "Pytest Integration"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        provider:
          - aws
          - do
    steps:
      - name: "Checkout Infrastructure"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Nebari
        run: |
          pip install .[dev]
          conda install --quiet --yes conda-build

      - name: Set Environment DO
        if: ${{ matrix.provider == 'do' }}
        run: |
          echo "NEBARI_K8S_VERSION=1.24.13-do.0" >> $GITHUB_ENV
          echo "DIGITALOCEAN_TOKEN=${{ secrets.DIGITALOCEAN_TOKEN }}" >> $GITHUB_ENV
          echo "SPACES_ACCESS_KEY_ID=${{ secrets.SPACES_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "SPACES_SECRET_ACCESS_KEY=${{ secrets.SPACES_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Set Environment AWS
        if: ${{ matrix.provider == 'aws' }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Integration Tests
        run: |
          pytest --version
          pytest tests_integration/ -vvv -s -m ${{ matrix.provider }}
