name: test publish

on:
  workflow_dispatch:
    inputs:
      qhub_tag:
        description: 'Tag for test PyPI release'
        required: True

jobs:
  test-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip build

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create tag
        run: git tag ${{ github.event.inputs.qhub_tag }}

      - name: Build source and binary
        run: python -m build --sdist --wheel .

      - name: Publish to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Test install from Test PyPI
        run: |
            pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple \
            qhub==${{ github.event.inputs.qhub_tag }}
