name: "Test Conda Build"

on:
  pull_request:
    paths:
      - ".github/workflows/test_conda_build.yaml"
      - "pyproject.toml"
  push:
    branches:
      - main
      - release/\d{4}.\d{1,2}.\d{1,2}
    paths:
      - ".github/workflows/test_conda_build.yaml"
      - "pyproject.toml"

jobs:
  test-conda-build:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}
    concurrency:
        group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
        cancel-in-progress: true
    steps:
      - name: "Checkout Infrastructure"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge
          activate-environment: nebari-dev
          conda-remove-defaults: true

      - name: Install dependencies
        run: |
          conda install grayskull conda-build conda-verify
          pip install build

      - name: Conda list
        run: |
          conda list

      - name: Generate sdist
        run: |
          python -m build --sdist

      - name: Generate meta.yaml
        run: |
          python -m grayskull pypi dist/*.tar.gz

      - name: Build conda package
        run: |
          conda build . --output-folder conda-bld

          # Store the path for the next step
          echo "CONDA_BLD_PATH=$(pwd)/conda-bld" >> $GITHUB_ENV

      - name: Test conda package
        run: |
          NEBARI_VERSION=$(conda search -c local --override-channels nebari --json | jq -r '.nebari[0].version')

          conda create -n test-env -c file://${{ env.CONDA_BLD_PATH }} "nebari=$NEBARI_VERSION"

          conda run -n test-env --live-stream nebari --version
